### ISSUE TITLE
Destructuring from useStoryblok() no longer working in SDK 5.1.2 during build - Typescript error

### ISSUE THREAD

**Issue by nebrekab** [storyblok/storyblok-astro#1066]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-astro

[![storyblok.com](https://a.storyblok.com/f/88751/1500x500/7974d6bc34/storyblok-astro.png)][storyblokurl]

We have upgraded to the SDK 5.1.2  from 5.0.2, and the destructuring of the content value from the useStoryBlok() response is now throwing a Typescript build error.

---

## Expected Behavior

No build error. :)

## Current Behavior

We receive the following build error:

```
src/pages/hub/categories/[slug].astro:60:9 - error ts(2339): Property 'content' does not exist on type 'ISbStoryData<ISbComponentType<string> & { [index: string]: any; }> | null'.

const { content } = await useStoryblok(
```

## Steps to Reproduce

1. Create a project with Astro 5.1.7+, Vite 6.0+ and the Astro SDK 5.1.2
2. Add some code to your Astro page (frontmatter/serverside code head area) fetch using useStoryblok() and try and destructured the content value - e.g.

```
---
import { useStoryblok } from '@storyblok/astro'
const {content} = await useStoryblok( 'cdn/stories', {version: 'draft'}, {}, Astro as any);
// access destructured var
console.log(content)
---
<p>Test page</p>
```

3. run `npm run build`

You should now see the errors

package.json example:
[package.json](https://github.com/user-attachments/files/18490035/package.json)

The current solution we have is to remove destructuring, but it would be good to have this working again to simplify our code.

**Comment by dipankarmaikap** [comment]
Closing this issue as `useStoryblok` has been removed in favor of `getLiveStory` in the latest release.
